#!/usr/bin/env node
// Extract the event ABIs the indexer decodes, straight from the compiled forge
// artifacts, and prove each one's topic0 equals the accepted schema signature.
//
// Hand-transcribing ABIs into the indexer would make the "independent
// reconstruction" claim depend on a transcription nobody checks. Generating them
// from the artifact and asserting the topic0 against the sdd.md §3.2 signature
// closes both halves: the shape comes from the compiler, and the identity is
// checked against the accepted text.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { toEventSelector } from 'viem';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const OUT = join(HERE, '..', 'abis');

// contract -> artifact path, and the events we consume with their accepted
// signatures (sdd.md §3.2). A signature listed here that the artifact does not
// produce, or produces at a different topic0, is a hard error.
const SOURCES = [
  {
    contract: 'Rig',
    artifact: 'out/Rig.sol/Rig.json',
    events: {
      Settled:
        'Settled(uint64,address,address,bool,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256)',
    },
  },
  {
    contract: 'HardReserve',
    artifact: 'out/HardReserve.sol/HardReserve.json',
    events: {
      Redeemed: 'Redeemed(address,address,uint256,uint256,uint256,uint256)',
      PreGenesisWethSanitized: 'PreGenesisWethSanitized(uint256)',
    },
  },
  {
    contract: 'StrategicTreasury',
    artifact: 'out/StrategicTreasury.sol/StrategicTreasury.json',
    events: {
      StrategicInflow: 'StrategicInflow(uint8,address,uint256)',
      StrategicOutflow: 'StrategicOutflow(uint8,address,address,uint256)',
      VyrfHarvest: 'VyrfHarvest(uint256,uint256)',
      VuxRevenueBurned: 'VuxRevenueBurned(uint256)',
      PolPositionChanged: 'PolPositionChanged(int8,uint256,uint256,uint128)',
      RevenueAllocated: 'RevenueAllocated(address,uint256,uint256,uint256,uint256)',
      LSGActivated: 'LSGActivated(address)',
      LSGDeactivated: 'LSGDeactivated(address)',
      StrategyAdmitted: 'StrategyAdmitted(address,address,uint256,uint8,uint64)',
    },
  },
  {
    contract: 'VUX',
    artifact: 'out/VUX.sol/VUX.json',
    events: { Transfer: 'Transfer(address,address,uint256)' },
  },
];

mkdirSync(OUT, { recursive: true });

const collected = {};
const checks = [];
let failed = 0;

for (const src of SOURCES) {
  const artifact = JSON.parse(readFileSync(join(REPO, src.artifact), 'utf8'));
  const abi = artifact.abi.filter((e) => e.type === 'event');
  const picked = [];

  for (const [name, signature] of Object.entries(src.events)) {
    const item = abi.find((e) => e.name === name);
    if (!item) {
      console.error(`FAIL ${src.contract}.${name}: not present in the compiled ABI`);
      failed++;
      continue;
    }
    // topic0 recomputed from the artifact's own shape...
    const fromArtifact = toEventSelector(item);
    // ...and from the accepted schema text, independently.
    const fromAccepted = toEventSelector(signature);
    const ok = fromArtifact === fromAccepted;
    if (!ok) failed++;
    checks.push({ contract: src.contract, name, ok, fromArtifact, fromAccepted });
    picked.push(item);
  }
  collected[src.contract] = picked;
}

for (const c of checks) {
  console.log(
    `${c.ok ? 'OK  ' : 'FAIL'} ${(c.contract + '.' + c.name).padEnd(38)} ${c.fromArtifact}${c.ok ? '' : `  != accepted ${c.fromAccepted}`}`
  );
}

if (failed) {
  console.error(`\n${failed} signature mismatch(es) — the indexer would decode the wrong shape. Refusing to write.`);
  process.exit(1);
}

const banner = `// GENERATED by scripts/extract-abis.mjs from the compiled forge artifacts.
// Do not edit by hand. Every topic0 below was verified against the accepted
// sdd.md §3.2 signature at generation time; re-run the script to re-verify.
`;
writeFileSync(
  join(OUT, 'vux-events.mjs'),
  banner + Object.entries(collected).map(([k, v]) => `export const ${k}Abi = ${JSON.stringify(v, null, 2)};`).join('\n\n') + '\n'
);

console.log(`\nWrote abis/vux-events.mjs — ${checks.length} events, all topic0 verified against the accepted schema.`);
